User.destroy_all
Grade.destroy_all
Subject.destroy_all
Material.destroy_all
require 'pry'

freshman = Grade.create(grade_level: 9)
sophomore = Grade.create(grade_level: 10)
junior = Grade.create(grade_level: 11)
senior = Grade.create(grade_level: 12)

10.times do
User.create(
  name: Faker::Name.name,
  age: Faker::Number.between(12, 18),
  grade_id: Grade.all.sample.id
)
end

chemistry = Subject.create(name: "Chemistry", grade_id: freshman.id)
earth_science = Subject.create(name: "Earth Science", grade_id: freshman.id)
ecology = Subject.create(name: "Ecology", grade_id: sophomore.id)
geology = Subject.create(name: "Geology", grade_id: sophomore.id)
anatomy = Subject.create(name: "Anatomy", grade_id: junior.id)
biology = Subject.create(name: "Biology", grade_id: junior.id)
physics = Subject.create(name: "Physics", grade_id: senior.id)
environmental_science = Subject.create(name: "Environmental Science", grade_id: senior.id)
world_religion = Subject.create(name: "World Religion", grade_id: freshman.id)
us_gov = Subject.create(name: "U.S. Government", grade_id: freshman.id)
geography = Subject.create(name: "Geography", grade_id: freshman.id)
european_history = Subject.create(name: "European History", grade_id: sophomore.id)
african_american_history = Subject.create(name: "African American History", grade_id: sophomore.id)
middle_eastern_history = Subject.create(name: "Middle Eastern History", grade_id: junior.id)
latin_american_studies = Subject.create(name: "Latin American Studies", grade_id: junior.id)
french_revolution = Subject.create(name: "French Revolution", grade_id: senior.id)
american_history = Subject.create(name: "American History", grade_id: senior.id)
public_speaking = Subject.create(name: "Public Speaking", grade_id: freshman.id)
british_literature = Subject.create(name: "British Literature", grade_id: sophomore.id)
american_literature = Subject.create(name: "American Literature", grade_id: junior.id)
greek_mythology = Subject.create(name: "Greek Mythology", grade_id: senior.id)
algebra = Subject.create(name: "Algebra", grade_id: freshman.id)
trigonometry = Subject.create(name: "Trigonometry", grade_id: freshman.id)
geometry = Subject.create(name: "Geometry", grade_id: sophomore.id)
statistics = Subject.create(name: "Statistics", grade_id: junior.id)
calculus = Subject.create(name: "Calculus", grade_id: senior.id)
political_science = Subject.create(name: "Political Science", grade_id: senior.id)
spanish = Subject.create(name: "Spanish", grade_id: junior.id)
french = Subject.create(name: "French", grade_id: junior.id)
art_history = Subject.create(name: "Art History", grade_id: senior.id)
psychology = Subject.create(name: "Psychology", grade_id: senior.id)
astronomy = Subject.create(name: "Astronomy", grade_id: sophomore.id)
economics = Subject.create(name: "Economics", grade_id: sophomore.id)

goggles = Material.create(name: "goggles", subject_id: chemistry.id)
stopwatch = Material.create(name: "stopwatch", subject_id: Subject.all.sample.id)
Material.create(name: "Chemistry: Matter and Change", subject_id: chemistry.id)
Material.create(name: "Science in our World Vol. 1", subject_id: earth_science.id)
Material.create(name: "Elements of Ecology 9th Edition", subject_id: ecology.id)
Material.create(name: "Geology Vol. 3", subject_id: geology.id)
Material.create(name: "Anatomy of the Human Body Vol 1.", subject_id: anatomy.id)
Material.create(name: "composition book", subject_id: Subject.all.sample.id)
Material.create(name: "Micro Biology 4th Edition", subject_id: biology.id)
Material.create(name: "Mechanical Physics Vol. 2", subject_id: physics.id)
Material.create(name: "Environmental Science Vol. 5", subject_id: environmental_science.id)
Material.create(name: "A People's History of the United States", subject_id: american_history.id)
Material.create(name: "World Religion Vol. 10", subject_id: world_religion.id)
Material.create(name: "United States Government 101", subject_id: us_gov.id)
Material.create(name: "World Geography Vol. 1", subject_id: geography.id)
Material.create(name: "A Timeline of European History 3rd Edition", subject_id: european_history.id)
Material.create(name: "African American History Vol. 3", subject_id: african_american_history.id)
Material.create(name: "Lebanon: A History Vol. 3", subject_id: middle_eastern_history.id)
Material.create(name: "Jesus Through Middle Eastern Eyes Vol. 1", subject_id: middle_eastern_history.id)
Material.create(name: "Latin American Art Vol. 1", subject_id: latin_american_studies.id)
Material.create(name: "The French Revolution Vol. 7", subject_id: french_revolution.id)
Material.create(name: "The Art of Speaking Vol. 3", subject_id: public_speaking.id)
Material.create(name: "Masters of British Literature Vol. 2", subject_id: british_literature.id)
Material.create(name: "American Literature Vol. 2", subject_id: american_literature.id)
Material.create(name: "Greek Mythology: An Introduction ", subject_id: greek_mythology.id)
Material.create(name: "Statistics Vol. 3", subject_id: statistics.id)
Material.create(name: "Graphing Calculator", subject_id: statistics.id)
Material.create(name: "Calculus Vol. 2", subject_id: calculus.id)
Material.create(name: "Graphing Calculator", subject_id: calculus.id)
Material.create(name: "Advanced Algebra Vol. 1", subject_id: algebra.id)
Material.create(name: "Graphing Calculator", subject_id: algebra.id)
Material.create(name: "Trigonometry Vol. 1", subject_id: trigonometry.id)
Material.create(name: "Graphing Calculator", subject_id: trigonometry.id)
Material.create(name: "Geometry and Functions Vol. 2", subject_id: geometry.id)
Material.create(name: "Graphing Calculator", subject_id: geometry.id)
Material.create(name: "Political Theory Vol. 1", subject_id: political_science.id)
Material.create(name: "Learning Spanish Vol. 3", subject_id: spanish.id)
Material.create(name: "Finding French 2nd Edition", subject_id: french.id)
Material.create(name: "Hisory of Modern Art Vol. 1", subject_id: art_history.id)
Material.create(name: "Psychology in Practice 1st Edition", subject_id: psychology.id)
Material.create(name: "Astronomy 101", subject_id: astronomy.id)
Material.create(name: "Intro to Economics", subject_id: economics.id)
